spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/crud_test
    username: crud
    password: crud

  jpa:
    hibernate:
      ddl-auto: update
  thymeleaf:
    cache: false
    prefix: classpath:/templates/